# Test GCS emulator

version: "3.0"
services:
  server:
    image: jwhitlock/gc-fake-storage:test
    volumes:
      - ./server/init_buckets:/data
      - ./server/storage:/storage
    environment:
      - GCS_FAKE_EXTERNAL_URL=https://server:4443

  client:
    build: ./client
    depends_on:
      - server
    environment:
      - SERVER_URL=https://server:4443
      - TEST_FILE_DIR=/files
    volumes:
      - ./client/files:/files
