# Test GCS emulator

version: "3.0"
services:
  server:
    build: https://github.com/jwhitlock/gc-fake-storage.git
    image: jwhitlock/gc-fake-storage
    volumes:
      - ./server/init_buckets:/data

  client:
    build: ./client
    depends_on:
      - server
    environment:
      - SERVER_URL=https://server:4443

